name: Cachy Music Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "15 */5 * * *"

concurrency:
  group: cachy-bot
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt update -qq
          sudo apt install -y -qq ffmpeg libopus0 python3 python3-pip python3-venv

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python packages
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -r requirements.txt

      - name: Create .env
        run: echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env

      - name: Setup cookies
        env:
          COOKIE_SECRET: ${{ secrets.YT_COOKIES }}
        run: |
          printf "%s" "$COOKIE_SECRET" | base64 -d > cookies.txt

      - name: Run bot
        env:
          YT_COOKIES_FILE: cookies.txt
        run: |
          . venv/bin/activate
          python main.py
